--- # Install gangserver on localhost
- hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: local

  tasks:
  - include: includes/python_modern_pip.yml

  # Set the timezone to Canberra
  - name: set the timezone to Canberra
    copy:
      src: files/timezone
      dest: /etc/timezone
      owner: root
      group: root
      mode: '0444'

  - name: install ntp
    apt:
      name: ntpdate
      state: latest

  - name: update time
    command: ntpdate -s time.nist.gov

  # Python dependancies
  - name: install python flask library
    command: pip3 install -U flask

  - name: install python flask-restful library
    command: pip3 install -U flask-restful

  # Install the server itself. We run the server from the git checkout
  # location.
  - name: copy gangserver systemd configuration
    copy:
      src: files/gangserver.systemd.service
      dest: /etc/systemd/system/gangserver.service
      owner: root
      group: root
      mode: '0444'

  # Install our advertisement mircoservice
  - name: copy gangadvert systemd configuration
    copy:
      src: files/gangadvert.systemd.service
      dest: /etc/systemd/system/gangadvert.service
      owner: root
      group: root
      mode: '0444'

  # Restart services
  - name: reload systemd itself
    command: systemctl daemon-reload

  - name: restart gangserver
    service:
      name: gangserver
      state: restarted
      enabled: yes

  - name: restart gangadvert
    service:
      name: gangadvert
      state: restarted
      enabled: yes
